name: Main
on: push

env:
  CI: true
  CACHE_VERSION: 3

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1.1.0
        with:
          version: 12
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('yarn.lock') }}-${{ env.CACHE_VERSION }}
      - name: Install dependencies
        run: yarn
      - name: Is the yarn.lock up-to-date?
        run: git diff --exit-code yarn.lock

  test:
    runs-on: ubuntu-latest
    needs: dependencies
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1.1.0
        with:
          version: 12
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('yarn.lock') }}-${{ env.CACHE_VERSION }}
      - name: Unit tests
        run: yarn test --coverage
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage/lcov.info

  lint:
    runs-on: ubuntu-latest
    needs: dependencies
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1.1.0
        with:
          version: 12
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('yarn.lock') }}-${{ env.CACHE_VERSION }}
      - name: Lint
        run: yarn lint

  build:
    runs-on: ubuntu-latest
    needs: dependencies
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1.1.0
        with:
          version: 12
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('yarn.lock') }}-${{ env.CACHE_VERSION }}
      - name: Build library
        run: yarn build
  
  build-storybook:
    runs-on: ubuntu-latest
    needs: dependencies
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1.1.0
        with:
          version: 12
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('yarn.lock') }}-${{ env.CACHE_VERSION }}
      - name: Cache storybook
        uses: actions/cache@v1
        with:
          path: storybook-static
          key: ${{ runner.OS }}-storybook-${{ github.run_number }}
      - name: Build storybook
        run: yarn build-storybook
  
  percy:
    runs-on: ubuntu-latest
    needs: [build-storybook]
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1.1.0
        with:
          version: 12
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('yarn.lock') }}-${{ env.CACHE_VERSION }}
      - name: Cache storybook
        uses: actions/cache@v1
        with:
          path: storybook-static
          key: ${{ runner.OS }}-storybook-${{ github.run_number }}
      - name: Percy
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
        run: yarn snapshot

  release:
    runs-on: ubuntu-latest
    needs: [dependencies, test, lint, build, build-storybook, percy]
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1.1.0
        with:
          version: 12
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('yarn.lock') }}-${{ env.CACHE_VERSION }}
      - name: Cache storybook
        uses: actions/cache@v1
        with:
          path: storybook-static
          key: ${{ runner.OS }}-storybook-${{ github.run_number }}
      - name: Build library
        run: yarn build
      - name: Release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: yarn semantic-release