name: Main
on: push

env:
  CI: true
  CACHE_VERSION: 0

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1.1.0
        with:
          version: 12
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('yarn.lock') }}-${{ env.CACHE_VERSION }}
      - name: Install dependencies
        run: yarn
      - name: Is the yarn.lock up-to-date?
        run: git diff --exit-code yarn.lock

  lint:
    runs-on: ubuntu-latest
    needs: dependencies
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1.1.0
        with:
          version: 12
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('yarn.lock') }}-${{ env.CACHE_VERSION }}
      - name: Lint
        run: yarn lint

  build:
    runs-on: ubuntu-latest
    needs: dependencies
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1.1.0
        with:
          version: 12
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('yarn.lock') }}-${{ env.CACHE_VERSION }}
      - name: Build library
        run: yarn build
  
  build-storybook:
    runs-on: ubuntu-latest
    needs: dependencies
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1.1.0
        with:
          version: 12
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('yarn.lock') }}-${{ env.CACHE_VERSION }}
      - name: Cache storybook
        uses: actions/cache@v1
        with:
          path: dist-storybook
          key: ${{ runner.OS }}-storybook-${{ github.run_number }}
      - name: Build storybook
        run: yarn build-storybook

  release:
    runs-on: ubuntu-latest
    needs: [dependencies, lint, build, build-storybook]
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1.1.0
        with:
          version: 12
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('yarn.lock') }}-${{ env.CACHE_VERSION }}
      - name: Cache storybook
        uses: actions/cache@v1
        with:
          path: dist-storybook
          key: ${{ runner.OS }}-storybook-${{ github.run_number }}
      - name: Build library
        run: yarn build
      - name: Release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: yarn semantic-release